version: '3.9'

services:
  todo-app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 5173:5173
      - 51204:51204
    volumes:
      - ./:/home/node/todo-app
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: todo-app-node
